package me.piepers.super11.domain.sportdeer;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.assertNotNull;

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

@RunWith(JUnit4.class)
public class UpcomingTest {

	@Test
	public void test_that_mapping_of_json_is_as_expected() throws Exception {
		Docs<Upcoming> docs = SportdeerMapper.from(this.generateExampleJsonString(), Upcoming.class);
		assertNotNull(docs);
		assertNotNull(docs.getData());
		List<Upcoming> list = docs.getData();
		assertThat(list.size(), is(30));
	}

	private String generateExampleJsonString() {
		return "{\r\n" + "    \"docs\": [\r\n" + "        {\r\n" + "            \"_id\": 282,\r\n"
				+ "            \"id_country\": 46,\r\n" + "            \"id_league\": 8,\r\n"
				+ "            \"id_season\": 2,\r\n" + "            \"id_stage\": 1,\r\n"
				+ "            \"fixture_status\": \"Postponed\",\r\n"
				+ "            \"fixture_status_short\": \"PSP\",\r\n" + "            \"id_team_season_away\": 14,\r\n"
				+ "            \"id_team_season_home\": 10,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"31\",\r\n"
				+ "            \"schedule_date\": \"2018-03-16T20:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Wembley\",\r\n"
				+ "            \"team_season_away_name\": \"Newcastle United\",\r\n"
				+ "            \"team_season_home_name\": \"Tottenham\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 325,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Postponed\",\r\n"
				+ "            \"fixture_status_short\": \"PSP\",\r\n" + "            \"id_team_season_away\": 5,\r\n"
				+ "            \"id_team_season_home\": 18,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"31\",\r\n"
				+ "            \"schedule_date\": \"2018-03-17T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"King Power Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Arsenal\",\r\n"
				+ "            \"team_season_home_name\": \"Leicester\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 355,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Postponed\",\r\n"
				+ "            \"fixture_status_short\": \"PSP\",\r\n" + "            \"id_team_season_away\": 2,\r\n"
				+ "            \"id_team_season_home\": 12,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"31\",\r\n"
				+ "            \"schedule_date\": \"2018-03-17T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Liberty Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Southampton\",\r\n"
				+ "            \"team_season_home_name\": \"Swansea\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 291,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Postponed\",\r\n"
				+ "            \"fixture_status_short\": \"PSP\",\r\n" + "            \"id_team_season_away\": 17,\r\n"
				+ "            \"id_team_season_home\": 20,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"31\",\r\n"
				+ "            \"schedule_date\": \"2018-03-18T13:30:00.000Z\",\r\n"
				+ "            \"stadium\": \"London Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Manchester United\",\r\n"
				+ "            \"team_season_home_name\": \"West Ham\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 329,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Postponed\",\r\n"
				+ "            \"fixture_status_short\": \"PSP\",\r\n" + "            \"id_team_season_away\": 19,\r\n"
				+ "            \"id_team_season_home\": 11,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"31\",\r\n"
				+ "            \"schedule_date\": \"2018-03-18T16:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Etihad Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Brighton\",\r\n"
				+ "            \"team_season_home_name\": \"Manchester City\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 290,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 9,\r\n"
				+ "            \"id_team_season_home\": 13,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T12:30:00.000Z\",\r\n"
				+ "            \"stadium\": \"Selhurst Park\",\r\n"
				+ "            \"team_season_away_name\": \"Liverpool\",\r\n"
				+ "            \"team_season_home_name\": \"Crystal Palace\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 297,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 3,\r\n"
				+ "            \"id_team_season_home\": 7,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Vicarage Road Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Bournemouth\",\r\n"
				+ "            \"team_season_home_name\": \"Watford\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 295,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 12,\r\n"
				+ "            \"id_team_season_home\": 17,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Old Trafford\",\r\n"
				+ "            \"team_season_away_name\": \"Swansea\",\r\n"
				+ "            \"team_season_home_name\": \"Manchester United\"\r\n" + "        },\r\n"
				+ "        {\r\n" + "            \"_id\": 312,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 18,\r\n"
				+ "            \"id_team_season_home\": 19,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"The American Express Community Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Leicester\",\r\n"
				+ "            \"team_season_home_name\": \"Brighton\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 332,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 16,\r\n"
				+ "            \"id_team_season_home\": 14,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"St James' Park\",\r\n"
				+ "            \"team_season_away_name\": \"Huddersfield\",\r\n"
				+ "            \"team_season_home_name\": \"Newcastle United\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 361,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 15,\r\n"
				+ "            \"id_team_season_home\": 1,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"The Hawthorns\",\r\n"
				+ "            \"team_season_away_name\": \"Burnley\",\r\n"
				+ "            \"team_season_home_name\": \"West Bromwich Albion\"\r\n" + "        },\r\n"
				+ "        {\r\n" + "            \"_id\": 357,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 2,\r\n"
				+ "            \"id_team_season_home\": 20,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"London Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Southampton\",\r\n"
				+ "            \"team_season_home_name\": \"West Ham\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 316,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 11,\r\n"
				+ "            \"id_team_season_home\": 6,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-03-31T17:30:00.000Z\",\r\n"
				+ "            \"stadium\": \"Goodison Park\",\r\n"
				+ "            \"team_season_away_name\": \"Manchester City\",\r\n"
				+ "            \"team_season_home_name\": \"Everton\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 299,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 4,\r\n"
				+ "            \"id_team_season_home\": 5,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-04-01T13:30:00.000Z\",\r\n"
				+ "            \"stadium\": \"Emirates Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Stoke\",\r\n"
				+ "            \"team_season_home_name\": \"Arsenal\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 334,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 10,\r\n"
				+ "            \"id_team_season_home\": 8,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"32\",\r\n"
				+ "            \"schedule_date\": \"2018-04-01T16:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Stamford Bridge\",\r\n"
				+ "            \"team_season_away_name\": \"Tottenham\",\r\n"
				+ "            \"team_season_home_name\": \"Chelsea\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 306,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 14,\r\n"
				+ "            \"id_team_season_home\": 18,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"King Power Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Newcastle United\",\r\n"
				+ "            \"team_season_home_name\": \"Leicester\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 333,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 10,\r\n"
				+ "            \"id_team_season_home\": 4,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Bet365 Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Tottenham\",\r\n"
				+ "            \"team_season_home_name\": \"Stoke\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 301,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 2,\r\n"
				+ "            \"id_team_season_home\": 5,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Emirates Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Southampton\",\r\n"
				+ "            \"team_season_home_name\": \"Arsenal\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 367,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 17,\r\n"
				+ "            \"id_team_season_home\": 11,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Etihad Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Manchester United\",\r\n"
				+ "            \"team_season_home_name\": \"Manchester City\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 304,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 20,\r\n"
				+ "            \"id_team_season_home\": 8,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Stamford Bridge\",\r\n"
				+ "            \"team_season_away_name\": \"West Ham\",\r\n"
				+ "            \"team_season_home_name\": \"Chelsea\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 365,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 13,\r\n"
				+ "            \"id_team_season_home\": 3,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Vitality Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Crystal Palace\",\r\n"
				+ "            \"team_season_home_name\": \"Bournemouth\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 340,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 9,\r\n"
				+ "            \"id_team_season_home\": 6,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Goodison Park\",\r\n"
				+ "            \"team_season_away_name\": \"Liverpool\",\r\n"
				+ "            \"team_season_home_name\": \"Everton\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 321,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 16,\r\n"
				+ "            \"id_team_season_home\": 19,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"The American Express Community Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Huddersfield\",\r\n"
				+ "            \"team_season_home_name\": \"Brighton\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 308,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 15,\r\n"
				+ "            \"id_team_season_home\": 7,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Vicarage Road Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Burnley\",\r\n"
				+ "            \"team_season_home_name\": \"Watford\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 344,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 12,\r\n"
				+ "            \"id_team_season_home\": 1,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"33\",\r\n"
				+ "            \"schedule_date\": \"2018-04-07T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"The Hawthorns\",\r\n"
				+ "            \"team_season_away_name\": \"Swansea\",\r\n"
				+ "            \"team_season_home_name\": \"West Bromwich Albion\"\r\n" + "        },\r\n"
				+ "        {\r\n" + "            \"_id\": 309,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 3,\r\n"
				+ "            \"id_team_season_home\": 9,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"34\",\r\n"
				+ "            \"schedule_date\": \"2018-04-14T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Anfield\",\r\n"
				+ "            \"team_season_away_name\": \"Bournemouth\",\r\n"
				+ "            \"team_season_home_name\": \"Liverpool\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 318,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 5,\r\n"
				+ "            \"id_team_season_home\": 14,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"34\",\r\n"
				+ "            \"schedule_date\": \"2018-04-14T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"St James' Park\",\r\n"
				+ "            \"team_season_away_name\": \"Arsenal\",\r\n"
				+ "            \"team_season_home_name\": \"Newcastle United\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 311,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 18,\r\n"
				+ "            \"id_team_season_home\": 15,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"34\",\r\n"
				+ "            \"schedule_date\": \"2018-04-14T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Turf Moor\",\r\n"
				+ "            \"team_season_away_name\": \"Leicester\",\r\n"
				+ "            \"team_season_home_name\": \"Burnley\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 339,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 6,\r\n"
				+ "            \"id_team_season_home\": 12,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"34\",\r\n"
				+ "            \"schedule_date\": \"2018-04-14T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"Liberty Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Everton\",\r\n"
				+ "            \"team_season_home_name\": \"Swansea\"\r\n" + "        },\r\n" + "        {\r\n"
				+ "            \"_id\": 351,\r\n" + "            \"id_country\": 46,\r\n"
				+ "            \"id_league\": 8,\r\n" + "            \"id_season\": 2,\r\n"
				+ "            \"id_stage\": 1,\r\n" + "            \"fixture_status\": \"Not started\",\r\n"
				+ "            \"fixture_status_short\": \"NS\",\r\n" + "            \"id_team_season_away\": 4,\r\n"
				+ "            \"id_team_season_home\": 20,\r\n" + "            \"number_goal_team_away\": 0,\r\n"
				+ "            \"number_goal_team_home\": 0,\r\n" + "            \"round\": \"34\",\r\n"
				+ "            \"schedule_date\": \"2018-04-14T15:00:00.000Z\",\r\n"
				+ "            \"stadium\": \"London Stadium\",\r\n"
				+ "            \"team_season_away_name\": \"Stoke\",\r\n"
				+ "            \"team_season_home_name\": \"West Ham\"\r\n" + "        }\r\n" + "    ],\r\n"
				+ "    \"pagination\": {\r\n" + "        \"total\": 76,\r\n" + "        \"limit\": 30,\r\n"
				+ "        \"page\": 1,\r\n" + "        \"pages\": 3\r\n" + "    }\r\n" + "}";
	}
}
